###Basic
GET http://localhost:1234

### GET All resources
GET http://localhost:1234/resources

### GET Colors resources
GET http://localhost:1234/resources/?category=colores

### POST New resource
POST http://localhost:1234/resources
Content-Type: application/json

{
   "name": "webGradients",
   "description" : "Aqui puedes tomar una utilizar una gran variedad de gradiente, o crearlos tu mismo!",
   "category": "gradientes",
   "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFjiYSo0RsI5DMTu-OgKc0uYvBBhipio6Cuw&s",
   "url": "https://webgradients.com/"
}

### PATCH Update resource by id
PATCH http://localhost:1234/resources/66c129fa222c34701b49c2c2
Content-Type: application/json

{
  "description": "una herramienta en línea para crear y explorar paletas de colores. Ideal para diseñadores que buscan combinaciones de colores rápidas y efectivas"
}

### DELETE resource by id
DELETE http://localhost:1234/resources/66c17b64c795338804c3f91d
